apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: services
  annotations:
    # This is the default but lets be explicit because we're
    # trying use waves to order resources in this app.
    argocd.argoproj.io/sync-wave: 0
spec:
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  oddbit.com/services: "true"
          - git:
              repoURL: https://github.com/larsks/kind-cluster.git
              revision: HEAD
              directories:
                - path: services/*
  template:
    metadata:
      name: "{{name}}-{{path.basename}}"
    spec:
      project: "cluster-{{name}}"
      source:
        repoURL: https://github.com/larsks/kind-cluster.git
        targetRevision: HEAD
        path: "{{path}}/overlays/common"
      destination:
        server: "{{server}}"
        namespace: "{{path.basename}}"
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: -1
          backoff:
            duration: 30s
            factor: 2
            maxDuration: 10m
