apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager

resources:
- ../../base
- clusterissuers/house.yaml
- clusterissuers/in-cluster.yaml

patches:
  - path: deployments/cert-manager_patch.yaml
  - path: deployments/cert-manager-cainjector_patch.yaml

configMapGenerator:
  - name: house-ca-cert
    files:
      - house_ca_root.pem=certs/root_ca.crt
