apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

commonLabels:
  app.kubernetes.io/instance: cluster1

patches:
  - target:
      kind: Ingress
      name: whoami
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: whoami.apps.cluster1.house
      - op: replace
        path: /spec/tls/0/hosts/0
        value: whoami.apps.cluster1.house
